version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /docs-app
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /examples/consumer
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /examples/registry-consumer
    schedule:
      interval: weekly
